### ISSUE TITLE
使用了自定义的ip pool后出错

### ISSUE THREAD

**Issue by sbw983** [NKUCodingCat/gogotester_python#11]
使用内置的的ggc.txt能正常使用，但是使用自定义的ip pool后出错
我的系统是ubuntu 16.04 
出错信息：
python Main_Gevent.py 
=========================

   WARNING: IP Protocol avaliblity has not been confirmed

   Strongly suggest to open it unless you 100% believe that your network support IPv4 and IPv6.

=========================
Generating the IP pool.......Please Wait
Traceback (most recent call last):
  File "Main_Gevent.py", line 43, in <module>
    ippool = ggc_ip.GGC_IP(root+"ggc.txt", Protocol_chk).IPPool
  File "/date/date0/Tools/FQ翻墙/Google/NKUCodingCat-gogotester_python-e0e6d44/src/ggc_ip.py", line 24, in __init__
    self.IPPool = [map(lambda x:x.int(), i) for i in [list(itertools.chain.from_iterable(j)) for j in map(lambda x:[list(i) for i in x], self.IPPool)]]
  File "/date/date0/Tools/FQ翻墙/Google/NKUCodingCat-gogotester_python-e0e6d44/src/ggc_ip.py", line 24, in <lambda>
    self.IPPool = [map(lambda x:x.int(), i) for i in [list(itertools.chain.from_iterable(j)) for j in map(lambda x:[list(i) for i in x], self.IPPool)]]
OverflowError: long int too large to convert to int

我自己的ip pool

***@***:/date/date0/Tools/FQ翻墙/Google/NKUCodingCat-gogotester_python-e0e
6d44/src$ cat ggc.txt 

#Use Sharp as comment
#V4
#Thanks for the IP list from xyuanmu@github 

99.198.128.0/17
89.207.224.0/24
85.187.222.0/24
84.235.77.0/24
8.8.8.0/24
8.8.4.0/24
8.35.200.0/21
8.35.192.0/21
8.34.216.0/21
8.34.208.0/21
74.125.90.0/23
74.125.88.0/23
74.125.71.0/24
74.125.70.0/24
74.125.69.0/24
74.125.68.0/24
74.125.6.0/24
74.125.39.0/24
74.125.31.0/24
74.125.30.0/24
74.125.29.0/24
74.125.28.0/24
74.125.27.0/24
74.125.26.0/24
74.125.25.0/24
74.125.24.0/24
74.125.239.0/24
74.125.238.0/24
74.125.237.0/24
74.125.236.0/24
74.125.235.0/24
74.125.234.0/24
74.125.233.0/24
74.125.232.0/24
74.125.231.0/24
74.125.230.0/24
74.125.23.0/24
74.125.229.0/24
74.125.228.0/24
74.125.227.0/24
74.125.226.0/24
74.125.225.0/24
74.125.224.0/24
74.125.22.0/24
74.125.21.0/24
74.125.206.0/24
74.125.205.0/24
74.125.204.0/24
74.125.203.0/24
74.125.202.0/24
74.125.201.0/24
74.125.200.0/24
74.125.199.0/24
74.125.198.0/24
74.125.196.0/24
74.125.195.0/24
74.125.193.0/24
74.125.192.0/24
74.125.143.0/24
74.125.142.0/24
74.125.141.0/24
74.125.140.0/24
74.125.139.0/24
74.125.138.0/24
74.125.135.0/24
74.125.134.0/24
74.125.133.0/24
74.125.132.0/24
74.125.131.0/24
74.125.130.0/24
74.125.129.0/24
74.125.128.0/24
74.125.127.0/24
74.125.126.0/24
74.125.0.0/18
74.125.0.0/16
72.14.192.0/18
70.32.151.0/24
70.32.148.0/23
70.32.146.0/23
70.32.145.0/24
70.32.144.0/24
70.32.142.0/23
70.32.140.0/23
70.32.136.0/24
70.32.132.0/23
70.32.131.0/24
70.32.128.0/23
70.32.128.0/19
66.249.72.0/24
66.249.64.0/19
66.102.4.0/24
66.102.3.0/24
66.102.2.0/24
66.102.12.0/24
66.102.1.0/24
66.102.0.0/20
64.9.252.0/22
64.9.248.0/22
64.9.244.0/22
64.9.243.0/24
64.9.242.0/24
64.9.241.0/24
64.9.240.0/24
64.9.236.0/22
64.9.228.0/23
64.9.225.0/24
64.9.224.0/24
64.233.191.0/24
64.233.190.0/24
64.233.189.0/24
64.233.188.0/24
64.233.187.0/24
64.233.186.0/24
64.233.185.0/24
64.233.184.0/24
64.233.183.0/24
64.233.182.0/24
64.233.181.0/24
64.233.180.0/24
64.233.179.0/24
64.233.178.0/24
64.233.177.0/24
64.233.176.0/24
64.233.171.0/24
64.233.169.0/24
64.233.168.0/24
64.233.167.0/24
64.233.166.0/24
64.233.165.0/24
64.233.164.0/24
64.233.163.0/24
64.233.162.0/24
64.233.161.0/24
64.233.160.0/24
64.233.160.0/19
45.56.0.0/18
41.244.244.0/24
35.204.0.0/15
35.200.0.0/14
35.192.0.0/13
35.184.0.0/13
23.255.128.0/17
23.251.128.0/19
23.236.48.0/20
23.228.128.0/18
223.27.237.0/24
216.58.223.0/24
216.58.222.0/24
216.58.221.0/24
216.58.220.0/24
216.58.219.0/24
216.58.218.0/24
216.58.217.0/24
216.58.216.0/24
216.58.215.0/24
216.58.214.0/24
216.58.213.0/24
216.58.212.0/24
216.58.211.0/24
216.58.210.0/24
216.58.209.0/24
216.58.208.0/24
216.58.200.0/24
216.58.192.0/19
216.252.222.0/24
216.252.221.0/24
216.252.220.0/24
216.252.220.0/22
216.239.60.0/24
216.239.39.0/24
216.239.38.0/24
216.239.36.0/24
216.239.35.0/24
216.239.34.0/24
216.239.33.0/24
216.239.32.0/24
216.239.32.0/19
216.21.160.0/20
209.85.235.0/24
209.85.234.0/24
209.85.233.0/24
209.85.232.0/24
209.85.203.0/24
209.85.202.0/24
209.85.201.0/24
209.85.200.0/24
209.85.147.0/24
209.85.145.0/24
209.85.144.0/24
209.85.128.0/17
209.107.182.0/23
209.107.176.0/23
209.107.176.0/20
208.68.108.0/22
207.223.160.0/20
199.223.232.0/21
199.192.112.0/22
197.199.254.0/24
197.199.253.0/24
193.200.222.0/24
192.200.224.0/19
192.178.0.0/15
192.158.28.0/22
192.119.28.0/24
192.119.16.0/20
192.104.160.0/23
185.25.30.0/24
185.25.28.0/23
185.150.148.0/22
173.255.112.0/20
173.194.79.0/24
173.194.78.0/24
173.194.77.0/24
173.194.76.0/24
173.194.74.0/24
173.194.73.0/24
173.194.72.0/24
173.194.70.0/24
173.194.7.0/24
173.194.69.0/24
173.194.68.0/24
173.194.67.0/24
173.194.66.0/24
173.194.64.0/24
173.194.63.0/24
173.194.53.0/24
173.194.47.0/24
173.194.46.0/24
173.194.45.0/24
173.194.44.0/24
173.194.43.0/24
173.194.42.0/24
173.194.41.0/24
173.194.40.0/24
173.194.39.0/24
173.194.38.0/24
173.194.37.0/24
173.194.36.0/24
173.194.35.0/24
173.194.34.0/24
173.194.33.0/24
173.194.32.0/24
173.194.223.0/24
173.194.222.0/24
173.194.221.0/24
173.194.220.0/24
173.194.219.0/24
173.194.218.0/24
173.194.217.0/24
173.194.216.0/24
173.194.215.0/24
173.194.214.0/24
173.194.213.0/24
173.194.212.0/24
173.194.211.0/24
173.194.210.0/24
173.194.209.0/24
173.194.208.0/24
173.194.207.0/24
173.194.206.0/24
173.194.205.0/24
173.194.204.0/24
173.194.203.0/24
173.194.202.0/24
173.194.201.0/24
173.194.200.0/24
173.194.199.0/24
173.194.198.0/24
173.194.197.0/24
173.194.196.0/24
173.194.195.0/24
173.194.194.0/24
173.194.193.0/24
173.194.192.0/24
173.194.175.0/24
173.194.142.0/24
173.194.141.0/24
173.194.140.0/24
173.194.136.0/24
173.194.132.0/24
173.194.127.0/24
173.194.126.0/24
173.194.125.0/24
173.194.124.0/24
173.194.121.0/24
173.194.120.0/24
173.194.119.0/24
173.194.118.0/24
173.194.117.0/24
173.194.113.0/24
173.194.112.0/24
173.194.0.0/16
172.253.0.0/16
172.217.9.0/24
172.217.8.0/24
172.217.7.0/24
172.217.6.0/24
172.217.5.0/24
172.217.4.0/24
172.217.30.0/24
172.217.3.0/24
172.217.29.0/24
172.217.28.0/24
172.217.27.0/24
172.217.26.0/24
172.217.25.0/24
172.217.24.0/24
172.217.23.0/24
172.217.22.0/24
172.217.21.0/24
172.217.20.0/24
172.217.2.0/24
172.217.19.0/24
172.217.18.0/24
172.217.17.0/24
172.217.16.0/24
172.217.15.0/24
172.217.14.0/24
172.217.13.0/24
172.217.12.0/24
172.217.11.0/24
172.217.10.0/24
172.217.1.0/24
172.217.0.0/24
172.217.0.0/16
172.102.9.0/24
172.102.8.0/24
172.102.8.0/21
172.102.14.0/23
172.102.12.0/23
172.102.11.0/24
172.102.10.0/24
164.40.244.0/24
162.222.176.0/21
162.216.148.0/22
146.88.60.0/24
146.148.0.0/17
142.250.0.0/15
136.32.0.0/11
136.22.1.0/24
136.22.0.0/24
136.22.0.0/23
130.211.0.0/16
111.92.162.0/24
108.59.80.0/20
108.177.98.0/24
108.177.97.0/24
108.177.96.0/24
108.177.9.0/24
108.177.8.0/24
108.177.7.0/24
108.177.4.0/23
108.177.30.0/24
108.177.22.0/24
108.177.21.0/24
108.177.20.0/24
108.177.2.0/24
108.177.18.0/23
108.177.15.0/24
108.177.14.0/24
108.177.13.0/24
108.177.120.0/24
108.177.12.0/24
108.177.119.0/24
108.177.112.0/24
108.177.11.0/24
108.177.104.0/24
108.177.103.0/24
108.177.10.0/24
108.177.0.0/17
108.170.232.0/21
108.170.192.0/18
107.188.128.0/17
107.178.192.0/18
107.167.160.0/19
104.196.0.0/14
104.154.0.0/15
104.134.241.0/24
104.134.240.0/24
104.133.7.0/24
104.133.6.0/24
104.133.5.0/24
104.133.4.0/24
104.133.2.0/23
104.133.1.0/24
104.133.0.0/24
104.132.98.0/24
104.132.8.0/24
104.132.7.0/24
104.132.69.0/24
104.132.65.0/24
104.132.62.0/24
104.132.61.0/24
104.132.6.0/24
104.132.59.0/24
104.132.57.0/24
104.132.56.0/24
104.132.52.0/24
104.132.51.0/24
104.132.5.0/24
104.132.43.0/24
104.132.42.0/24
104.132.41.0/24
104.132.40.0/24
104.132.38.0/24
104.132.37.0/24
104.132.34.0/24
104.132.33.0/24
104.132.30.0/24
104.132.3.0/24
104.132.29.0/24
104.132.27.0/24
104.132.26.0/24
104.132.25.0/24
104.132.227.0/24
104.132.222.0/24
104.132.216.0/24
104.132.215.0/24
104.132.214.0/24
104.132.213.0/24
104.132.212.0/24
104.132.211.0/24
104.132.210.0/24
104.132.21.0/24
104.132.209.0/24
104.132.207.0/24
104.132.206.0/24
104.132.205.0/24
104.132.203.0/24
104.132.202.0/24
104.132.201.0/24
104.132.200.0/24
104.132.20.0/24
104.132.199.0/24
104.132.198.0/24
104.132.196.0/24
104.132.192.0/24
104.132.190.0/24
104.132.19.0/24
104.132.189.0/24
104.132.187.0/24
104.132.186.0/24
104.132.184.0/24
104.132.183.0/24
104.132.180.0/24
104.132.18.0/24
104.132.179.0/24
104.132.178.0/24
104.132.177.0/24
104.132.176.0/24
104.132.174.0/24
104.132.171.0/24
104.132.17.0/24
104.132.169.0/24
104.132.168.0/24
104.132.167.0/24
104.132.166.0/24
104.132.165.0/24
104.132.164.0/24
104.132.163.0/24
104.132.162.0/24
104.132.161.0/24
104.132.160.0/24
104.132.159.0/24
104.132.155.0/24
104.132.153.0/24
104.132.152.0/24
104.132.151.0/24
104.132.150.0/24
104.132.149.0/24
104.132.146.0/24
104.132.144.0/24
104.132.142.0/24
104.132.141.0/24
104.132.140.0/24
104.132.139.0/24
104.132.138.0/24
104.132.136.0/24
104.132.135.0/24
104.132.132.0/24
104.132.130.0/24
104.132.128.0/24
104.132.126.0/24
104.132.125.0/24
104.132.124.0/24
104.132.120.0/24
104.132.12.0/24
104.132.119.0/24
104.132.118.0/24
104.132.117.0/24
104.132.116.0/24
104.132.114.0/24
104.132.113.0/24
104.132.11.0/24
104.132.100.0/24
104.132.0.0/23
104.132.0.0/14
103.25.178.0/24

2c0f:fb50::/32
2c0f:fb50:4003::/48
2c0f:fb50:4002::/48
2a03:ace0::/32
2a03:ace0:100::/40
2a00:79e1:abc::/46
2a00:79e0::/32
2a00:79e0:101::/48
2a00:1450::/32
2800:3f0::/32
2800:3f0:4005::/48
2800:3f0:4004::/48
2800:3f0:4003::/48
2800:3f0:4002::/48
2800:3f0:4001::/48
2620:f0:4002::/48
2620:f0:4001::/48
2620:f0:4000::/48
2620:f0:4000::/44
2620:15c::/36
2620:0:1000::/40
2607:f8b0::/32
2607:f8b0:4016::/48
2607:f8b0:4015::/48
2607:f8b0:4014::/48
2607:f8b0:4013::/48
2607:f8b0:4012::/48
2607:f8b0:4011::/48
2607:f8b0:4010::/48
2607:f8b0:400f::/48
2607:f8b0:400e::/48
2607:f8b0:400d::/48
2607:f8b0:400c::/48
2607:f8b0:400b::/48
2607:f8b0:400a::/48
2607:f8b0:4009::/48
2607:f8b0:4008::/48
2607:f8b0:4007::/48
2607:f8b0:4006::/48
2607:f8b0:4005::/48
2607:f8b0:4004::/48
2607:f8b0:4003::/48
2607:f8b0:4002::/48
2607:f8b0:4001::/48
2607:f8b0:4000::/48
2605:ef80:c0::/42
2605:ef80::/32
2605:ef80:80::/42
2605:ef80:40::/42
2605:ef80:200::/42
2605:ef80:140::/42
2605:a601::/32
2605:a600::/31
2604:ca00:f::/48
2604:ca00:f004::/48
2604:ca00:f003::/48
2604:ca00:f002::/48
2604:ca00:f001::/48
2600:1900::/28
2404:6800::/32
2404:6800:400a::/48
2404:6800:4009::/48
2404:6800:4008::/48
2404:6800:4007::/48
2404:6800:4006::/48
2404:6800:4005::/48
2404:6800:4004::/48
2404:6800:4003::/48
2404:6800:4002::/48
2404:6800:4001::/48
2401:fa00::/32
2401:fa00:44::/48
2401:fa00:43::/48
2401:fa00:42::/48
2401:fa00:41::/48
2401:fa00:40::/48
2400:6280:5::/48
2001:680:4004::/48
2001:4860::/32
2001:4860:4805::/48

看样子是我的ip pool文件太大了，gogotest处理不了?

**Comment by sbw983** [comment]
上周一块硬盘突然废了，所有数据都没法找回来，只能从头找google ip了。
ip pool来源：
http://bgp.he.net/search?search%5Bsearch%5D=google&commit=Search

**Comment by NKUCodingCat** [comment]
我大概一年不看gayhub了。。。。
读研使我秃头。。。。
我记得好像是不支持v6？我现在都用ss也不管这个了。。。
