### ISSUE TITLE
XP最新版运行错误

### ISSUE THREAD

**Issue by ghost** [NKUCodingCat/gogotester_python#3]
E:\gogotester_python\packed>python27.exe Main_Gevent.py
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "Main_Gevent.py", line 27, in <module>
    import ggc_ip
  File "E:\gogotester_python\packed\python27.zip\zipextimporter.py", line 82, in
 load_module
  File "E:\gogotester_python\packed\dependence.egg\ggc_ip.py", line 5, in <modul
e>
  File "E:\gogotester_python\packed\python27.zip\zipextimporter.py", line 82, in
 load_module
  File "E:\gogotester_python\packed\dependence.egg\Con_Test.py", line 1, in <mod
ule>
ImportError: No module named urllib2
请按任意键继续. . .

**Comment by NKUCodingCat** [comment]
= =擦忘记把urllib2放进去了……

**Comment by NKUCodingCat** [comment]
再试试吧，更新了一下
