### ISSUE TITLE
AttributeError: 'module' object has no attribute 'IPSet'

### ISSUE THREAD

**Issue by zjhxmjl** [NKUCodingCat/gogotester_python#4]
Hi,骚年！what's wrong?
Os:Fedora 20
Python:2.7.5
This is error info:

[zjhxmjl@localhost packed]$ python Main_Gevent.py 
Traceback (most recent call last):
  File "Main_Gevent.py", line 42, in <module>
    ippool = ggc_ip.GGC_IP(root+"ggc.txt").IPPool
  File "/home/zjhxmjl/Downloads/goagent/local/gogotester_python/packed/dependence.egg/ggc_ip.py", line 10, in **init**
  File "/home/zjhxmjl/Downloads/goagent/local/gogotester_python/packed/dependence.egg/ggc_ip.py", line 108, in GGCIPS
AttributeError: 'module' object has no attribute 'IPSet'

**Comment by NKUCodingCat** [comment]
嘛……氖的IPy是不是版本不太对_(:з」∠)_

**Comment by NKUCodingCat** [comment]
我回去测试一下Orz

**Comment by NKUCodingCat** [comment]
你可以试着把python27.zip里面的IPy.py放到packages.egg/noarch里面，虽然我觉得不太有什么用但是值得试试，以及不行的话你pip装一个IPy吧因为这个报错实在是看不出来哪有问题

**Comment by zjhxmjl** [comment]
OMG,i'll try it

**Comment by zjhxmjl** [comment]
Resloved,you right!Got it,thks 骚年！

**Comment by NKUCodingCat** [comment]
嘛……如此便好
